=== priyankayadav98/WSD_CAT1/employee_demo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<em:schema xmlns:em ="http://www.w3.org/2001/XMLSchema">
	<em:element name="Company" type="Employees" />
    <em:complexType name="Employees">
      <em:sequence>
         <em:element name="Employee" type="Emp" minOccurs="1" maxOccurs="unbounded" />	
      </em:sequence>
    </em:complexType>
    
    <em:complexType name="Emp">
      <em:sequence>
         <em:element name="Emp-name" type="em:string" />
         <em:element name="Emp-age" type="em:integer" />
         <em:element name="Emp-salary" type="mysalary" />
         <em:element name="Emp-emailid" type="emailAddress" />
         <em:element name="Emp-Phonenum" type="em:integer" />
         <em:element name="Emp-designation" type="em:string" />
      </em:sequence>
      <ems:attribute name="Emp_ID" type="ems:ID" use="required" />
      
      
    </em:complexType>
    
    <em:simpleType name="mysalary">
      <em:restriction base="em:decimal">
         <em:minInclusive value="50000" />
         <em:maxInclusive value="200000" />
      </em:restriction>
   </em:simpleType>
   
    <em:simpleType name="emailAddress"> 
    <em:restriction base="em:string"> 
      <em:pattern value="[^@]+@[^\.]+\..+"/> 
    </em:restriction> 
  </em:simpleType> 
    
</em:schema>

=== priyankayadav98/WSD_CAT1/NewFile.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="style.xsl" ?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="employee_demo.xsd">
  <Employee Emp_ID ="101">
    <Emp-name>VIKASH</Emp-name>
    <Emp-age>32</Emp-age>
    <Emp-salary>70000</Emp-salary>
    <Emp-emailid>ABC@GMAIL.COM</Emp-emailid>
    <Emp-Phonenum>9076854321</Emp-Phonenum>
    <Emp-designation>MANAGER</Emp-designation>
  </Employee>
  <Employee Emp_ID="102">
    <Emp-name>VIMAL</Emp-name>
    <Emp-age>22</Emp-age>
    <Emp-salary>50000</Emp-salary>
    <Emp-emailid>XYZ@GMAIL.COM</Emp-emailid>
    <Emp-Phonenum>9076854391</Emp-Phonenum>
    <Emp-designation>SOFTWARE DEV</Emp-designation>
  </Employee>
  <Employee Emp_ID="103">
    <Emp-name>ANISH</Emp-name>
    <Emp-age>21</Emp-age>
    <Emp-salary>100000</Emp-salary>
    <Emp-emailid>WER@GMAIL.COM</Emp-emailid>
    <Emp-Phonenum>9076054321</Emp-Phonenum>
    <Emp-designation>DESIGNER</Emp-designation>
  </Employee>
  <Employee Emp_ID= "104">
    <Emp-name>SINCHAN</Emp-name>
    <Emp-age>42</Emp-age>
    <Emp-salary>78000</Emp-salary>
    <Emp-emailid>YCV@GMAIL.COM</Emp-emailid>
    <Emp-Phonenum>9076804321</Emp-Phonenum>
    <Emp-designation>TESTER</Emp-designation>
  </Employee>
</Company>
